version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Postgres
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postges
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
